spring:
  application:
    name: jwt-auth-demo

server:
  port: 8080

logging:
  level:
    root: INFO
    com.hdfc.jwtauth: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"

login:
  rate-limit:
    limit-for-period: 5
    limit-refresh-period: 1m
    timeout-duration: 0s

  circuit-breaker:
    failure-rate-threshold: 50
    slow-call-rate-threshold: 100
    wait-duration-in-open-state: 30s
    slow-call-duration-threshold: 2s
    permitted-number-of-calls-in-half-open-state: 3
    minimum-number-of-calls: 5
    sliding-window-size: 10


resilience4j:

  ratelimiter:
    instances:
      loginRateLimiter:
        limitForPeriod: 5
        limitRefreshPeriod: 1m
        timeoutDuration: 0s
        registerHealthIndicator: true

  circuitbreaker:

    instances:
      loginCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true

