spring:
  application:
    name: smart-authentication-backend
  mvc:
    throw-exception-if-no-handler-found: true

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    root: INFO
    com.hdfclife.smartauth: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"

login:
  rate-limit:
    limit-for-period: 5
    limit-refresh-period: 1m
    timeout-duration: 0s
